version: "3.9"

###############################################################################
# Réseau unique : tous les conteneurs se résolvent par leur nom (kafka, …)
###############################################################################
networks:
  data: {}

###############################################################################
# Volumes persistants : logs Kafka, données ZooKeeper, base PostgreSQL
###############################################################################
volumes:
  zkdata:       {}
  kafka-logs:   {}
  pgdata:       {}

###############################################################################
# Services infrastructure
###############################################################################
services:
  # -------------------------------------------------------------------------
  # 1. ZooKeeper
  # -------------------------------------------------------------------------
  zookeeper:
    build: ./zookeeper               # ⇢ infra/zookeeper/Dockerfile
    container_name: zookeeper
    networks: [data]
    volumes:
      - zkdata:/data                 # dataDir pour ZK
    environment:
      - ZOO_PORT=2181
    ports:
      - "2181:2181"                  # accès depuis le poste hôte (optionnel)

  # -------------------------------------------------------------------------
  # 2. Broker Kafka (connecté à ZooKeeper)
  # -------------------------------------------------------------------------
  kafka:
    build: ./kafka                   # ⇢ infra/kafka/Dockerfile
    container_name: kafka
    depends_on: [zookeeper]
    networks: [data]
    volumes:
      - kafka-logs:/tmp/kafka-logs   # logs & données du broker
    ports:
      - "9092:9092"                  # PLAINTEXT exposé
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1


  # -------------------------------------------------------------------------
  # 3. PostgreSQL (base cible)
  # -------------------------------------------------------------------------
  postgres:
    build: ./postgres                # ⇢ infra/postgres/Dockerfile
    container_name: postgres
    networks: [data]
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=openfood
      - POSTGRES_USER=ingest
      - POSTGRES_PASSWORD=ingestpwd
